# Generated by Django 4.2.1 on 2023-05-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Link',
            new_name='Links',
        ),
    ]
